name: build master
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: configure
      run: .github/action_scripts/configure.sh
    - name: cmake & make
      run: .github/action_scripts/make.sh
    - name: make tests
      run: .github/action_scripts/make_tests.sh